class Autogenerated {
  Result result;
  bool status;

  Autogenerated({this.result, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result.toJson();
    }
    data['status'] = this.status;
    return data;
  }
}

class Result {
  String sId;
  List<Site> site;

  Result({this.sId, this.site});

  Result.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    if (json['site'] != null) {
      site = new List<Site>();
      json['site'].forEach((v) {
        site.add(new Site.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    if (this.site != null) {
      data['site'] = this.site.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Site {
  String siteType;
  int area;
  Financial financial;
  String address;
  String street;
  String district;
  String state;
  String country;
  String zip;
  Location location;
  List<Sensor> sensor;
  String tel;
  String fax;
  String email;
  Contact contact;
  String image;
  List<Floor> floor;

  Site(
      {this.siteType,
      this.area,
      this.financial,
      this.address,
      this.street,
      this.district,
      this.state,
      this.country,
      this.zip,
      this.location,
      this.sensor,
      this.tel,
      this.fax,
      this.email,
      this.contact,
      this.image,
      this.floor});

  Site.fromJson(Map<String, dynamic> json) {
    siteType = json['site_type'];
    area = json['area'];
    financial = json['financial'] != null
        ? new Financial.fromJson(json['financial'])
        : null;
    address = json['address'];
    street = json['street'];
    district = json['district'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    location = json['location'] != null
        ? new Location.fromJson(json['location'])
        : null;
    if (json['sensor'] != null) {
      sensor = new List<Sensor>();
      json['sensor'].forEach((v) {
        sensor.add(new Sensor.fromJson(v));
      });
    }
    tel = json['tel'];
    fax = json['fax'];
    email = json['email'];
    contact =
        json['contact'] != null ? new Contact.fromJson(json['contact']) : null;
    image = json['image'];
    if (json['floor'] != null) {
      floor = new List<Floor>();
      json['floor'].forEach((v) {
        floor.add(new Floor.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['site_type'] = this.siteType;
    data['area'] = this.area;
    if (this.financial != null) {
      data['financial'] = this.financial.toJson();
    }
    data['address'] = this.address;
    data['street'] = this.street;
    data['district'] = this.district;
    data['state'] = this.state;
    data['country'] = this.country;
    data['zip'] = this.zip;
    if (this.location != null) {
      data['location'] = this.location.toJson();
    }
    if (this.sensor != null) {
      data['sensor'] = this.sensor.map((v) => v.toJson()).toList();
    }
    data['tel'] = this.tel;
    data['fax'] = this.fax;
    data['email'] = this.email;
    if (this.contact != null) {
      data['contact'] = this.contact.toJson();
    }
    data['image'] = this.image;
    if (this.floor != null) {
      data['floor'] = this.floor.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Financial {
  int tariff;
  double touRate;

  Financial({this.tariff, this.touRate});

  Financial.fromJson(Map<String, dynamic> json) {
    tariff = json['tariff'];
    touRate = json['tou_rate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['tariff'] = this.tariff;
    data['tou_rate'] = this.touRate;
    return data;
  }
}

class Location {
  double lat;
  double lng;
  String detail;

  Location({this.lat, this.lng, this.detail});

  Location.fromJson(Map<String, dynamic> json) {
    lat = json['lat'];
    lng = json['lng'];
    detail = json['detail'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['lat'] = this.lat;
    data['lng'] = this.lng;
    data['detail'] = this.detail;
    return data;
  }
}

class Sensor {
  String name;
  String serialNumber;
  Location location;

  Sensor({this.name, this.serialNumber, this.location});

  Sensor.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    serialNumber = json['serial_number'];
    location = json['location'] != null
        ? new Location.fromJson(json['location'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['serial_number'] = this.serialNumber;
    if (this.location != null) {
      data['location'] = this.location.toJson();
    }
    return data;
  }
}

class Contact {
  String name;
  String role;
  String tel;
  String email;

  Contact({this.name, this.role, this.tel, this.email});

  Contact.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    role = json['role'];
    tel = json['tel'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['role'] = this.role;
    data['tel'] = this.tel;
    data['email'] = this.email;
    return data;
  }
}

class Floor {
  int floorNo;
  String name;
  List<Sensor> sensor;
  List<Department> department;

  Floor({this.floorNo, this.name, this.sensor, this.department});

  Floor.fromJson(Map<String, dynamic> json) {
    floorNo = json['floor_no'];
    name = json['name'];
    if (json['sensor'] != null) {
      sensor = new List<Sensor>();
      json['sensor'].forEach((v) {
        sensor.add(new Sensor.fromJson(v));
      });
    }
    if (json['department'] != null) {
      department = new List<Department>();
      json['department'].forEach((v) {
        department.add(new Department.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['floor_no'] = this.floorNo;
    data['name'] = this.name;
    if (this.sensor != null) {
      data['sensor'] = this.sensor.map((v) => v.toJson()).toList();
    }
    if (this.department != null) {
      data['department'] = this.department.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Department {
  String name;
  List<Room> room;

  Department({this.name, this.room});

  Department.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    if (json['room'] != null) {
      room = new List<Room>();
      json['room'].forEach((v) {
        room.add(new Room.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    if (this.room != null) {
      data['room'] = this.room.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Room {
  String name;
  String image;
  List<Sensor> sensor;

  Room({this.name, this.image, this.sensor});

  Room.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    image = json['image'];
    if (json['sensor'] != null) {
      sensor = new List<Sensor>();
      json['sensor'].forEach((v) {
        sensor.add(new Sensor.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['image'] = this.image;
    if (this.sensor != null) {
      data['sensor'] = this.sensor.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
